### PR TITLE
feat(docusaurus): accept docusaurus updates

### PR DESCRIPTION
**Pull request by lpillonel**
This closes issue #49

- support for docusaurus 3.5.X
- added missing prettier to devDependencies

## Change Summary
docusaurus dependencies versions where loosened (`"3.4.0"` => `"^3.4.0"`), so any version >= 3.4.0 and < 5 is now accepted.

## PR Checklist

- [x] I have read and signed the [Contributor License Agreement](https://forms.gle/PZyiY5N2GDQU8GsV9).

### CODE REVIEW

**Comment by jasonbosco** [comment]
@lpillonel Thank you for the PR, but in the past, when we didn't pin the exact versions of docusaurus and related dependencies to the same one used in the main docusaurus project, it would cause errors due to multiple copies of React being loaded. See #10. 

So it would be great if you can pin the versions explicitly to 3.5.1.

**Review by jasonbosco — CHANGES_REQUESTED** [review]
@lpillonel Thank you for the PR, but in the past, when we didn't pin the exact versions of docusaurus and related dependencies to the same one used in the main docusaurus project, it would cause errors due to multiple copies of React being loaded. See #10. 

So it would be great if you can pin the versions explicitly to 3.5.1.

**Comment by joostdecock** [comment]
I have the same problem, but docusaurus has moved on to 3.5.2 now.

If it needs to be locked to the exact docusaurus version -- not uncommon for a plugin -- would it perhaps make sense to adopt their version.
This way if you are running docusaurus `x.y.z` you know you'll be ok if you also run docusaurus-theme-search-typesense `x.y.z`.

**Comment by lpillonel** [comment]
> in the past, when we didn't pin the exact versions of docusaurus and related dependencies to the same one used in the main docusaurus project, it would cause errors due to multiple copies of React being loaded. See #10.

I published for our needs a package (`@lpi/docusaurus-theme-search-typesense`) with this change and I have noticed no such issue of multiples copy of react in our project. I also double checked in the `package-lock.json` (one copy of react installed). Actually there is no pinned version of react as a dependency for any of the packages loaded in our project.

If there was an error two years back around this, it might be maybe something wrong about docusaurus dependencies ?

**Comment by jasonbosco** [comment]
I see, ok open to giving this a shot. I'll merge this and publish a new version shortly.

**Comment by jasonbosco** [comment]
This is now available in `v0.22.0-1`.

**Pull request merged**
