### PR TITLE
Upgrade for Docusaurus 3.2.0

### PR DESCRIPTION
**Pull request by fharper**
## Change Summary

Upgrade for Docusaurus 3.2.0

## PR Checklist

- [X] I have read and signed the [Contributor License Agreement](https://forms.gle/PZyiY5N2GDQU8GsV9).

### CODE REVIEW

**Review by jasonbosco — APPROVED** [review]

**Comment by jasonbosco** [comment]
Thank you for the PR!

**Comment by jasonbosco** [comment]
Published this in `0.17.0-0`. Could you give it a shot and let me know how it goes?

**Comment by fharper** [comment]
It's working fine so far, thanks.

**Comment by jasonbosco** [comment]
Thank you for confirming. Released `0.17.0`.

**Comment by jasonbosco** [comment]
@timolagus Could you open a new PR for this?

**Comment by fharper** [comment]
@timolagus I can create a PR at https://github.com/typesense/docusaurus-theme-search-typesense/pull/44 .

**Comment by jasonbosco** [comment]
Thanks @fharper. I've merged and published it

**Pull request merged**
