### PR TITLE
support docusaurus 3.5.2

### PR DESCRIPTION
**Pull request by fharper**
## Change Summary

Support for Docusaurus 3.5.2

## PR Checklist

- [X] I have read and signed the [Contributor License Agreement](https://forms.gle/PZyiY5N2GDQU8GsV9).

### CODE REVIEW

**Comment by fharper** [comment]
@jasonbosco any update on this PR? Sorry to ping you after a week, but I need this to upgrade Docusaurus :)

**Comment by jasonbosco** [comment]
@fharper I just published this in `0.21.0-0`. Could you give it a shot and let me know how it goes?

**Comment by fharper** [comment]
@jasonbosco not sure why this commit was missing part of the file (changed on my laptop, just not committed...), but you need to do another release with https://github.com/typesense/docusaurus-theme-search-typesense/pull/52 sorry

**Comment by jasonbosco** [comment]
I included that commit in `0.22.0-1`. I see it on npm in package.json: https://www.npmjs.com/package/docusaurus-theme-search-typesense/v/0.22.0-1?activeTab=code

**Pull request merged**
